#!/bin/sh
g++ -g -o md5_calc.o -c md5_calc.cc &&
g++ -g -o createUpdateXML.o -c createUpdateXML.cc &&
g++ -g -o utils.o -c utils.cc &&
g++ -Wall -Werror -g -Wno-unknown-pragmas -Wno-format -o tinystr.o -c tinystr.cpp &&
g++ -Wall -Werror -g -Wno-unknown-pragmas -Wno-format -o tinyxmlerror.o -c tinyxmlerror.cpp &&
g++ -Wall -Werror -g -Wno-unknown-pragmas -Wno-format -o tinyxml.o -c tinyxml.cpp &&
g++ -Wall -Werror -g -Wno-unknown-pragmas -Wno-format -o tinyxmlparser.o -c tinyxmlparser.cpp &&
g++ -g -o createUpdateXML md5_calc.o createUpdateXML.o utils.o tinystr.o tinyxmlerror.o tinyxml.o tinyxmlparser.o -lcrypto -lssl -lcurl &&
rm -rf *.o
