#!/bin/sh
g++ -g -D__DEBUG__ -o md5_calc.o -c md5_calc.cc &&
g++ -g -D__DEBUG__ -o downloadfile.o -c downloadfile.cc &&
g++ -g -D__DEBUG__ -o utils.o -c utils.cc &&
g++ -Wall -Werror -g -D__DEBUG__ -Wno-unknown-pragmas -Wno-format -o tinystr.o -c tinystr.cpp &&
g++ -Wall -Werror -g -D__DEBUG__ -Wno-unknown-pragmas -Wno-format -o tinyxmlerror.o -c tinyxmlerror.cpp &&
g++ -Wall -Werror -g -D__DEBUG__ -Wno-unknown-pragmas -Wno-format -o tinyxml.o -c tinyxml.cpp &&
g++ -Wall -Werror -g -D__DEBUG__ -Wno-unknown-pragmas -Wno-format -o tinyxmlparser.o -c tinyxmlparser.cpp &&
g++ -g -D__DEBUG__ -o downloadfile md5_calc.o downloadfile.o utils.o tinystr.o tinyxmlerror.o tinyxml.o tinyxmlparser.o -lcrypto -lssl -lcurl &&
rm -rf *.o
