#
#  VI: set ts=4; set expandtab; retab
#
#  Written 2011 by fU9ANg
#

# which c compiler
CC      = cc -g -D_DFA

# all exercise
ALL:
	$(CC) -o 4-01 4-01.c
	$(CC) -o 4-02 4-02.c
	$(CC) -o 4-03 4-03.c
	$(CC) -o 4-04 4-04.c
	$(CC) -o 4-05 4-05.c
	$(CC) -o 4-06 4-06.c
	$(CC) -o 4-07 4-07.c
	$(CC) -o 4-08 4-08.c
	$(CC) -o 4-09 4-09.c
	$(CC) -o 4-10 4-10.c
	$(CC) -o 4-11 4-11.c
	$(CC) -o 4-12 4-12.c
	$(CC) -o 4-13 4-13.c
	$(CC) -o 4-14 4-14.c

# clean all
clean:
	-rm -f 4-01 4-02 4-03 4-04 4-05 \
           4-06 4-07 4-08 4-09 4-10 \
           4-11 4-12 4-13 4-14
