#
#  VI: set ts=4; set expandtab; retab
#
#  Written 2011 by fU9ANg
#

# which c compiler
CC      = cc -g -D_DFA

# all exercise
ALL:
	$(CC) -o 3-01 3-01.c
	$(CC) -o 3-02 3-02.c
	$(CC) -o 3-03 3-03.c
	$(CC) -o 3-04 3-04.c
	$(CC) -o 3-05 3-05.c
	$(CC) -o 3-06 3-06.c

# clean all
clean:
	-rm -f 3-01 3-02 3-03 3-04 3-05 3-06
