// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/updatecontent.proto

#ifndef PROTOBUF_protocol_2fupdatecontent_2eproto__INCLUDED
#define PROTOBUF_protocol_2fupdatecontent_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protocol_2fupdatecontent_2eproto();
void protobuf_AssignDesc_protocol_2fupdatecontent_2eproto();
void protobuf_ShutdownFile_protocol_2fupdatecontent_2eproto();

class updatecontent;

// ===================================================================

class updatecontent : public ::google::protobuf::Message {
 public:
  updatecontent();
  virtual ~updatecontent();

  updatecontent(const updatecontent& from);

  inline updatecontent& operator=(const updatecontent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const updatecontent& default_instance();

  void Swap(updatecontent* other);

  // implements Message ----------------------------------------------

  updatecontent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const updatecontent& from);
  void MergeFrom(const updatecontent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string xmlcontent = 1;
  inline bool has_xmlcontent() const;
  inline void clear_xmlcontent();
  static const int kXmlcontentFieldNumber = 1;
  inline const ::std::string& xmlcontent() const;
  inline void set_xmlcontent(const ::std::string& value);
  inline void set_xmlcontent(const char* value);
  inline void set_xmlcontent(const char* value, size_t size);
  inline ::std::string* mutable_xmlcontent();
  inline ::std::string* release_xmlcontent();
  inline void set_allocated_xmlcontent(::std::string* xmlcontent);

  // @@protoc_insertion_point(class_scope:updatecontent)
 private:
  inline void set_has_xmlcontent();
  inline void clear_has_xmlcontent();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* xmlcontent_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_protocol_2fupdatecontent_2eproto();
  friend void protobuf_AssignDesc_protocol_2fupdatecontent_2eproto();
  friend void protobuf_ShutdownFile_protocol_2fupdatecontent_2eproto();

  void InitAsDefaultInstance();
  static updatecontent* default_instance_;
};
// ===================================================================


// ===================================================================

// updatecontent

// required string xmlcontent = 1;
inline bool updatecontent::has_xmlcontent() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void updatecontent::set_has_xmlcontent() {
  _has_bits_[0] |= 0x00000001u;
}
inline void updatecontent::clear_has_xmlcontent() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void updatecontent::clear_xmlcontent() {
  if (xmlcontent_ != &::google::protobuf::internal::kEmptyString) {
    xmlcontent_->clear();
  }
  clear_has_xmlcontent();
}
inline const ::std::string& updatecontent::xmlcontent() const {
  return *xmlcontent_;
}
inline void updatecontent::set_xmlcontent(const ::std::string& value) {
  set_has_xmlcontent();
  if (xmlcontent_ == &::google::protobuf::internal::kEmptyString) {
    xmlcontent_ = new ::std::string;
  }
  xmlcontent_->assign(value);
}
inline void updatecontent::set_xmlcontent(const char* value) {
  set_has_xmlcontent();
  if (xmlcontent_ == &::google::protobuf::internal::kEmptyString) {
    xmlcontent_ = new ::std::string;
  }
  xmlcontent_->assign(value);
}
inline void updatecontent::set_xmlcontent(const char* value, size_t size) {
  set_has_xmlcontent();
  if (xmlcontent_ == &::google::protobuf::internal::kEmptyString) {
    xmlcontent_ = new ::std::string;
  }
  xmlcontent_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* updatecontent::mutable_xmlcontent() {
  set_has_xmlcontent();
  if (xmlcontent_ == &::google::protobuf::internal::kEmptyString) {
    xmlcontent_ = new ::std::string;
  }
  return xmlcontent_;
}
inline ::std::string* updatecontent::release_xmlcontent() {
  clear_has_xmlcontent();
  if (xmlcontent_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = xmlcontent_;
    xmlcontent_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void updatecontent::set_allocated_xmlcontent(::std::string* xmlcontent) {
  if (xmlcontent_ != &::google::protobuf::internal::kEmptyString) {
    delete xmlcontent_;
  }
  if (xmlcontent) {
    set_has_xmlcontent();
    xmlcontent_ = xmlcontent;
  } else {
    clear_has_xmlcontent();
    xmlcontent_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protocol_2fupdatecontent_2eproto__INCLUDED
