// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/version.proto

#ifndef PROTOBUF_protocol_2fversion_2eproto__INCLUDED
#define PROTOBUF_protocol_2fversion_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protocol_2fversion_2eproto();
void protobuf_AssignDesc_protocol_2fversion_2eproto();
void protobuf_ShutdownFile_protocol_2fversion_2eproto();

class version;

// ===================================================================

class version : public ::google::protobuf::Message {
 public:
  version();
  virtual ~version();

  version(const version& from);

  inline version& operator=(const version& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const version& default_instance();

  void Swap(version* other);

  // implements Message ----------------------------------------------

  version* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const version& from);
  void MergeFrom(const version& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string ver = 1;
  inline bool has_ver() const;
  inline void clear_ver();
  static const int kVerFieldNumber = 1;
  inline const ::std::string& ver() const;
  inline void set_ver(const ::std::string& value);
  inline void set_ver(const char* value);
  inline void set_ver(const char* value, size_t size);
  inline ::std::string* mutable_ver();
  inline ::std::string* release_ver();
  inline void set_allocated_ver(::std::string* ver);

  // @@protoc_insertion_point(class_scope:version)
 private:
  inline void set_has_ver();
  inline void clear_has_ver();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* ver_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_protocol_2fversion_2eproto();
  friend void protobuf_AssignDesc_protocol_2fversion_2eproto();
  friend void protobuf_ShutdownFile_protocol_2fversion_2eproto();

  void InitAsDefaultInstance();
  static version* default_instance_;
};
// ===================================================================


// ===================================================================

// version

// required string ver = 1;
inline bool version::has_ver() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void version::set_has_ver() {
  _has_bits_[0] |= 0x00000001u;
}
inline void version::clear_has_ver() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void version::clear_ver() {
  if (ver_ != &::google::protobuf::internal::kEmptyString) {
    ver_->clear();
  }
  clear_has_ver();
}
inline const ::std::string& version::ver() const {
  return *ver_;
}
inline void version::set_ver(const ::std::string& value) {
  set_has_ver();
  if (ver_ == &::google::protobuf::internal::kEmptyString) {
    ver_ = new ::std::string;
  }
  ver_->assign(value);
}
inline void version::set_ver(const char* value) {
  set_has_ver();
  if (ver_ == &::google::protobuf::internal::kEmptyString) {
    ver_ = new ::std::string;
  }
  ver_->assign(value);
}
inline void version::set_ver(const char* value, size_t size) {
  set_has_ver();
  if (ver_ == &::google::protobuf::internal::kEmptyString) {
    ver_ = new ::std::string;
  }
  ver_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* version::mutable_ver() {
  set_has_ver();
  if (ver_ == &::google::protobuf::internal::kEmptyString) {
    ver_ = new ::std::string;
  }
  return ver_;
}
inline ::std::string* version::release_ver() {
  clear_has_ver();
  if (ver_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ver_;
    ver_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void version::set_allocated_ver(::std::string* ver) {
  if (ver_ != &::google::protobuf::internal::kEmptyString) {
    delete ver_;
  }
  if (ver) {
    set_has_ver();
    ver_ = ver;
  } else {
    clear_has_ver();
    ver_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protocol_2fversion_2eproto__INCLUDED
