#
#  VI: set ts=4; set expandtab; retab
#
#  Written 2011 by fU9ANg
#

# which c compiler
CC      = cc -g -D_DFA

# all exercise
ALL:
	$(CC) -o 2-01 2-01.c
	$(CC) -o 2-02 2-02.c
	$(CC) -o 2-03 2-03.c
	$(CC) -o 2-04 2-04.c
	$(CC) -o 2-05 2-05.c
	$(CC) -o 2-06 2-06.c
	$(CC) -o 2-07 2-07.c
	$(CC) -o 2-08 2-08.c
	$(CC) -o 2-09 2-09.c
	$(CC) -o 2-10 2-10.c

# clean all
clean:
	-rm -f 2-01 2-02 2-03 2-04 2-05 \
           2-06 2-07 2-08 2-09 2-10 \
           *.o
